### PR TITLE
Add redirect to /sites if user is logged in

### PR DESCRIPTION
**Pull request by Vigasaurus**
Fixes [#297](https://github.com/plausible/analytics/discussions/297)

### CODE REVIEW

**Comment by ukutaht** [comment]
I think we only want the redirect on the `index.html` page or on the `/` route.

That way logged-in users can still read our articles, see the `/contact` and `/data-policy` pages etc.

**Comment by Vigasaurus** [comment]
Yeah makes sense heh - I don't know why I didn't even consider that 😛

**Comment by ukutaht** [comment]
Thanks!

**Comment by ukutaht** [comment]
I've noticed the `logged_in` cookie doesn't always persist as I'd hoped. I think it's because we don't set an expiration on that cookie which means it doesn't stick around https://stackoverflow.com/a/532660

**Comment by ukutaht** [comment]
just a note for myself to fix but if you're looking for something to do @Vigasaurus :)

**Comment by Vigasaurus** [comment]
@ukutaht it should be long enough now? :)
image

**Comment by ukutaht** [comment]
5000 years is plenty :D

**Pull request merged**
