### PR TITLE
Allow for collaborators to have a reproducible environment

### PR DESCRIPTION
**Pull request by hirusi**
Adds a simple file for contributing, locks Node, npm, and Ruby versions.

### CODE REVIEW

**Comment by ukutaht** [comment]
Great, thanks!

Looks like Netlify isn't able to build with these changes, full log below:

```
7:42:57 AM: Build ready to start
7:42:59 AM: build-image version: c6001ed68662a13e5deb24abec2b46058c58248a
7:42:59 AM: build-image tag: v3.9.0
7:42:59 AM: buildbot version: f650485c830eb31597911322420b99299a4303b8
7:42:59 AM: Fetching cached dependencies
7:42:59 AM: Starting to download cache of 257.1MB
7:43:01 AM: Finished downloading cache in 1.36266693s
7:43:01 AM: Starting to extract cache
7:43:08 AM: Finished extracting cache in 7.137373422s
7:43:08 AM: Finished fetching cache in 8.568390837s
7:43:08 AM: Starting to prepare the repo for build
7:43:08 AM: Preparing Git Reference pull/282/head
7:43:09 AM: Parsing package.json dependencies
7:43:10 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: '_site' versus '_site/' in the Netlify UI
7:43:10 AM: Starting build script
7:43:10 AM: Installing dependencies
7:43:10 AM: Python version set to 2.7
7:43:11 AM: Started restoring cached node version
7:43:14 AM: Finished restoring cached node version
7:43:15 AM: v10.24.1 is already installed.
7:43:15 AM: Now using node v10.24.1 (npm v6.14.12)
7:43:15 AM: Started restoring cached build plugins
7:43:15 AM: Finished restoring cached build plugins
7:43:15 AM: Attempting ruby version 2.6.2, read from environment
7:43:17 AM: Using ruby version 2.6.2
7:43:17 AM: Using bundler version 2.0.1 from Gemfile.lock
7:43:18 AM: Successfully installed bundler-2.0.1
7:43:18 AM: 1 gem installed
7:43:18 AM: Using PHP version 5.6
7:43:18 AM: Started restoring cached ruby gems
7:43:18 AM: Finished restoring cached ruby gems
7:43:18 AM: Started restoring cached node modules
7:43:18 AM: Finished restoring cached node modules
7:43:18 AM: Installing NPM modules using NPM version 6.14.12
7:43:19 AM: npm ERR! code ENOTSUP
7:43:19 AM: npm ERR! notsup Unsupported engine for plausible-website@1.0.0: wanted: {"node":"^14.17","npm":"^7.24"} (current: {"node":"10.24.1","npm":"6.14.12"})
7:43:19 AM: npm ERR! notsup Not compatible with your version of node/npm: plausible-website@1.0.0
7:43:19 AM: npm ERR! notsup Not compatible with your version of node/npm: plausible-website@1.0.0
7:43:19 AM: npm ERR! notsup Required: {"node":"^14.17","npm":"^7.24"}
7:43:19 AM: npm ERR! notsup Actual:   {"npm":"6.14.12","node":"10.24.1"}
7:43:19 AM: npm ERR! A complete log of this run can be found in:
7:43:19 AM: npm ERR!     /opt/buildhome/.npm/_logs/2021-09-28T05_43_19_447Z-debug.log
7:43:19 AM: Error during NPM install
7:43:19 AM: Build was terminated: Build script returned non-zero exit code: 1
7:43:19 AM: Creating deploy upload records
7:43:19 AM: Failing build: Failed to build site
7:43:19 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
7:43:19 AM: Finished processing build request in 19.826458412s
```

Any idea what could cause this?

**Comment by hirusi** [comment]
Correct...

> Required: {"node":"^14.17","npm":"^7.24"}
> Actual: {"npm":"6.14.12","node":"10.24.1"}

Node v10 is [EOL](https://nodejs.org/en/about/releases/). I would recommend at least updating to Node v12, and ideally v14.

**Comment by hirusi** [comment]
Forestry is using Node 10 as well for its preview server.

I could also revise the Ruby version to the latest `2.6.x`.

**Comment by hirusi** [comment]
This time Jekyll fails, hmm...

> npm ERR! notsup Unsupported engine for plausible-website@1.0.0: wanted: {"node":"^10.24.1","npm":"^6.14.12"} (current: {"node":"12.22.1","npm":"6.14.12"})

**Pull request merged**
